language: go

go:
    - 1.3
    - release
    - tip

install:
    - go get -d -v ./... && go build -v ./...
    - go get github.com/stretchr/testify/assert
    - go get github.com/ory-am/common
    - go get code.google.com/p/go-uuid/uuid

script: go test ./...